<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Localities seed.
 */
class LocalitiesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'name' => '*Audio/Video*',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '2',
                'name' => '*Registration*',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '3',
                'name' => '*Speaking*',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '4',
                'name' => 'Arcadia/Alhambra',
                'preferred_conference' => 'A',
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '5',
                'name' => 'Bakersfield',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '6',
                'name' => 'Baldwin Park',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '7',
                'name' => 'Cerritos',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '8',
                'name' => 'Chula Vista',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '9',
                'name' => 'Cypress/Anaheim',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '10',
                'name' => 'Diamond Bar',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '11',
                'name' => 'East Los Angeles',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '12',
                'name' => 'Ft Collins/Denver',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '13',
                'name' => 'FTTA',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '14',
                'name' => 'Fullerton',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '15',
                'name' => 'Garden Grove',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '16',
                'name' => 'Huntington Beach',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '17',
                'name' => 'Irvine',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '18',
                'name' => 'Long Beach',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '19',
                'name' => 'Los Angeles/UCLA',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '20',
                'name' => 'Los Angeles/USC',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '22',
                'name' => 'Monterey Park',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '23',
                'name' => 'Moreno Valley',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '24',
                'name' => 'Ontario',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '25',
                'name' => 'Orange',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '26',
                'name' => 'Pasadena',
                'preferred_conference' => 'B',
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '27',
                'name' => 'Phoenix',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '28',
                'name' => 'Riverside',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '29',
                'name' => 'San Bernardino',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '30',
                'name' => 'San Diego',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '31',
                'name' => 'San Juan Capistrano',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '32',
                'name' => 'San Luis Obispo',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '34',
                'name' => 'Santa Ana',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '35',
                'name' => 'Santa Barbara',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '36',
                'name' => 'Santa Monica',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '37',
                'name' => 'South Gate',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '38',
                'name' => 'Torrance',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '39',
                'name' => 'Tucson',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '40',
                'name' => 'Victorville',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '41',
                'name' => 'Vista',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '42',
                'name' => 'Yorba Linda',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '43',
                'name' => 'Las Vegas',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '44',
                'name' => 'Other',
                'preferred_conference' => NULL,
                'comment' => 'All other localities',
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '45',
                'name' => 'Honolulu',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '46',
                'name' => 'Thousand Oaks',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '47',
                'name' => 'Los Angeles/CSUN',
                'preferred_conference' => 'A',
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '48',
                'name' => '*Medical Staff*',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
            [
                'id' => '49',
                'name' => 'San Marcos',
                'preferred_conference' => NULL,
                'comment' => NULL,
                'creator' => NULL,
                'created' => '2021-12-12 00:00:00',
                'modifier' => NULL,
                'modified' => '2021-12-12 00:00:00',
            ],
        ];

        $table = $this->table('localities');
        $table->insert($data)->save();
    }
}
